### ISSUE TITLE
Add testing for python27

### ISSUE THREAD

**Issue by cerdman** [ryannjohnson/django-schemas#6]
I wasn't sure if this was something that just won't work with 2.7 --- or if it was just a matter of settings up the Travis CI and/or tox build matrices for doing both 2.7 and 3.4

**Comment by ryannjohnson** [comment]
I'm pretty certain that the tests fail at 3.3 and below, without even trying 2.7 yet. I'll run that test tonight (Pacific Time) and get back with a diagnosis.

**Comment by ryannjohnson** [comment]
I only had to change a few lines and Python 2.7.9 on Travis (and 2.7.3 locally) passed the tests. I just pushed a new version to pypi with the changes.
