### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PolygonField'

### ISSUE THREAD

**Issue by livelifelively** [ryannjohnson/django-schemas#7]
I am using django-schemas for postgis. My models definitions are as follows.

```
class Geo(models.Model):

    gid = models.AutoField(primary_key=True)
    state = models.CharField(max_length=80)
    pc = models.PositiveSmallIntegerField()
    pc_name = models.CharField(max_length=80)
    ac = models.PositiveSmallIntegerField()
    ac_name = models.CharField(max_length=80)
    geom = models.PolygonField()
    name = models.CharField(max_length=80)
    state_name = models.CharField(max_length=80)
    district_name = models.CharField(max_length=80)
    region = models.PolygonField()

    def object_method(self):
        pass

    class Meta:
        db_environment = 'regions_environment'

```

But when starting the server or running the migrations, it gives following error "AttributeError: 'module' object has no attribute 'PolygonField'". Are the model functions of geodjango supported in the module? If not, how can we define model fields to use with POSTGIS? Thanks...

**Comment by ryannjohnson** [comment]
I think this should fix it: https://github.com/ryannjohnson/django-schemas#engine

In your `DATABASES` settings variable, change `ENGINE` for any applicable databases to `django_schemas.backends.postgis.wrapper`.

**Comment by livelifelively** [comment]
I am using the same. 

```
DATABASES = {
    'default': {
        # 'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'ENGINE': 'django_schemas.backends.postgis.wrapper',
        'NAME': '*******',
    	'USER': '*******',
    	'PASSWORD': '*******',
    	'HOST': 'localhost',
    	'PORT': '',
        'ENVIRONMENTS': [
            'regions_environment',
        ],
    }
}
```

**Comment by livelifelively** [comment]
Went through the code base, I think I have got the reason of the problem.

in case of geo-django, we are using following line to import models.
`from django.contrib.gis.db import models`

while with django_schemas we are using models as 
`from django_schemas import models`

in django_schemas/models.py we are importing models from django.db in line
`from django.db import models as django_models`

Meaning that django_schema is going to work for postgres but not postgis, since the gis models are defined else where and hence not extended here... 

Its a guess, will test this... and share result.

**Comment by ryannjohnson** [comment]
You're right! That import prevents models from properly inheriting from `django.contrib.gis.db.models`.

To accommodate this, I've altered how django-schemas gets implemented into the models. Instead of using `django_schemas.models` for everything django-related, models must now inherit from `django_schemas.models.Model` and django's models seperately.

Refer to this example for postgis: https://github.com/ryannjohnson/django-schemas#postgis-models

**Comment by livelifelively** [comment]
It worked. In file django_schema/models.py Changed
`from django.db import models as django_models`
to
`from django.contrib.gis.db import models as django_models`
