### ISSUE TITLE
Getting blank SQL from migrations

### ISSUE THREAD

**Issue by Algomorph** [ryannjohnson/django-schemas#8]
No idea what's going on, but I'm getting blank SQL from migrations like this when using django_schemas:
```SQL
BEGIN;
--
-- Create model Proposal
--

COMMIT;
```
Here is the code for the migration:
```python
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_tablespace': 'data',
                'db_table': 'proposal',
                'db_environment': 'research2',
            },
            bases=(django_schemas.models.Model, models.Model),
        ),
    ]
```

Here is code for the model:
```python
from django.db import models
from django_schemas.models import Model as SchemaModel


# Create your models here.
class Proposal(SchemaModel, models.Model):
    title = models.CharField(max_length=200)

    class Meta:
        db_tablespace = 'data'
        db_table = 'proposal'
        db_environment = 'research2'
```

Here is my settings.py file:
```python
"""
Django settings for vpr_webtools project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'scrambled_for_display_purposes'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hello.apps.HelloConfig',
    'faculty_reports.apps.FacultyReportsConfig',
    'django_schemas'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vpr_webtools.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vpr_webtools.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_schemas.backends.postgres.wrapper',
        'NAME': 'vpr',
        'USER': 'db_user',
        'PASSWORD': 'v1p2r3',
        'HOST': '128.8.172.192',
        'PORT': '5432',
        'ENVIRONMENTS': [
            'research',
            'research2',
            'contacts'
        ]
    }
}

DATABASE_ENVIRONMENTS = {
    'research': {
        'SCHEMA_NAME': 'research',
        'ADDITIONAL_SCHEMAS': ['public']
    },
    'research2': {
        'SCHEMA_NAME': 'research2',
        'ADDITIONAL_SCHEMAS': ['public']
    },
    'contacts': {
        'SCHEMA_NAME': 'contacts',
        'ADDITIONAL_SCHEMAS': ['public']
    },
}

DATABASE_ROUTERS = [
    'django_schemas.routers.ExplicitRouter',
]

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

```

When I comment-out the DATABASE_ROUTERS, I get a normal SQL file, but that doesn't contain the proper schema.
I'm on Python 3.5, Django 1.9, and Postgres 9.4.
Any idea what I'm doing wrong or how to fix it?

**Comment by ryannjohnson** [comment]
Does it work if you use the following commands?

```sh
$ python manage.py migrate_schema default --environment research
$ python manage.py migrate_schema default --environment research2
$ python manage.py migrate_schema default --environment contacts
```

**Comment by Algomorph** [comment]
I tried these, they execute without error, but don't affect the generated SQL in any way.

**Comment by ryannjohnson** [comment]
Ok. I'll give it a whirl this evening (PST) and get back to you on my findings.

**Comment by Algomorph** [comment]
Thanks

**Comment by ryannjohnson** [comment]
I just ran it locally, and if your `public` schema has a `django_migrations` table (like mine did), then Django will think that migrations were already run on that schema.

The quick fix would be to remove the `ADDITIONAL_SCHEMAS` from your `research2` environment on `settings.py`. Alternatively, you could refrain from running migrations on the `public` schema (which happens if Django's `migrate` command is ever run).

Or I could be way off. Let me know :)

**Comment by Algomorph** [comment]
Thanks, I'll give it a try. Unfortunately, I can only do so next Wednesday.

**Comment by Algomorph** [comment]
That seems to have worked, thanks. I'm still getting blank SQL migrations using the sqlmigrate command, but I guess I didn't realize that I don't need to use that after the migrate_schema, i.e. migrate_schema does everything that's needed. I'll keep this open for a bit longer today just to make sure that everything is working fine, not just rudimentary testing models.

**Comment by Algomorph** [comment]
Woo-hoo! It all worked out! :+1: 
I had a hiccup in one spot where migrate_schema was having trouble: it was trying to create a table in the _research_ schema that had a foreign key to a table in the _contacts_ schema. I just added the _contacts_ schema to the 'ADDITIONAL_SCHEMAS' of the _research_ schema, and added both schemas to the database user's search_path. That took care of the issue. Might be a point worth mentioning in the README.

**Comment by ryannjohnson** [comment]
Thinking through this, I'm guessing that all the migrations for the `research` schema are actually registered on the `contacts` schema's `django_migrations` table. This would happen since the `search_path` includes both schemas, and `contacts` would already have a `django_migrations` table available. This may lead to unpredictable behavior as the program grows or more cross-schema foreign keys are created.

Assuming that this project's models each occur once on any database instance, I'd recommend using the solution at http://stackoverflow.com/a/1628855/5307109 instead of django-schemas; this *should* allow you to maintain foreign keys and stable migrations. Schemas would be designated explicitly with the table names during migrations instead of implicitly via the `search_path`. The schemas themselves would have to be created manually.

**Comment by Algomorph** [comment]
Thanks, @ryannjohnson , I've seen that SO post, but if you look at the comments, Ghislain Leveque claims that it will fail for crating indexes, and I heavily use indexes in my schemata, so I'm weary of that.
The real solution is to modify django_schemas to account for cross-schema FKs somehow. There is also [django-boardinghouse](http://django-boardinghouse.readthedocs.io/en/latest/index.html) to try. IMHO, you guys should probably collaborate :-)

**Comment by ryannjohnson** [comment]
Thanks for following up @Algomorph. 

I guess to shed a little light on django-schema's opinionation, it's initial purpose was to fulfill the function described here: http://www.craigkerstiens.com/2012/11/30/sharding-your-database/. It's good for me to hear about your use case though, since I'd never considered using schemas with foreign keys; from a sharding perspective, they don't make sense if a schema might move to a different database instance altogether. 

The current implementation of django-schemas on migrations is a thin `search_path` wrapper on the database connection, and then Django executes the migration as it normally would. To accommodate foreign keys  while avoiding table name collisions would (probably) require modifying Django's migration functionality, which is currently out of the scope of this project. 

---

Regarding the SO answer, I was able to successfully migrate a model + index + constraint on a non-standard schema. I don't have enough SO rep to make a comment there :( but I think the language-use on that answer was misleading and should be clarified. Here's what I used:

```py
# models.py

from django.db import models

class Poll(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    another = models.IntegerField(unique=True)
    
    class Meta:
        db_table = 'alternate_schema"."polls'
```

And upon inspection:

```
django_schemas_8=# \d
                                 List of relations
      Schema      |               Name                |   Type   |      Owner
------------------+-----------------------------------+----------+------------------
 alternate_schema | polls                             | table    | django_schemas_8
 alternate_schema | polls_id_seq                      | sequence | django_schemas_8
```

```
django_schemas_8=# \d+ polls
                            Table "alternate_schema.polls"
 Column  |          Type          |                     Modifiers
---------+------------------------+----------------------------------------------------
 id      | integer                | not null default nextval('polls_id_seq'::regclass)
 name    | character varying(255) | not null
 another | integer                | not null
Indexes:
    "polls_pkey" PRIMARY KEY, btree (id)
    "polls_another_key" UNIQUE CONSTRAINT, btree (another)
    "alternate_schema_polls_name_5750c8ef_like" btree (name varchar_pattern_ops)
    "alternate_schema_polls_name_5750c8ef_uniq" btree (name)

```

**Comment by Algomorph** [comment]
@ryannjohnson thanks a lot for the insight. Now I feel somewhat more encouraged to use the naming solution. I'll stick to django_schemas for now ("don't fix it unless it's broken"), but I'll migrate to the naming thing if anything seriously breaks down.

**Comment by Algomorph** [comment]
@ryannjohnson , I decided to switch to the 'alt_schema"."table_name' solution, but now, whenever I run `migrate` after `sqlmigrate`, it reports errors of this kind:

> django.db.utils.ProgrammingError: syntax error at or near "."
> LINE 1: CREATE INDEX "research"."activity_type_b068931c" ON "research"."activity_type"

How did you get it to work?

**Comment by ryannjohnson** [comment]
@Algomorph Not sure - it just worked for me. Here's the project I used to test it with: http://ryannjohnson.com/downloads/2016-06-01-01_myproject.tar.bz2. I only ran `migrate`.
